/*
 *  Airline Application
BOOKING.java Christian Matei chri
stian.matei@icloud.com
 */

// importing the package 
package airlineapp.GUI;

// importing the libraries
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;
import java.util.Scanner;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import airlineapp.GUI.MAINTENACE;
import airlineapp.GUI.HOME;

/**
 *
 * @author Christian
 */

public class BOOKING extends javax.swing.JFrame {

    /**
     * Creates new form BOOKING
     * @throws java.io.FileNotFoundException
     */
    public BOOKING() throws FileNotFoundException {
        initComponents();
        
        ButtonGroup B = new ButtonGroup();
        
        B.add(RADOneway);
        B.add(RADReturn);
        
        RADOneway.setSelected(true);
      
       
        CMBOXDeparture1.setSelectedIndex(-1);
        CMBDestination1.setSelectedIndex(-1);	
         enableLeg2(false);
       
       
    
        
    }
    

    
    public void enableLeg2(boolean enable) {
		CMBOXDeparture1.setEnabled(enable);
		CMBDestination1.setEnabled(enable);
		
		CMBOXDeparture1.setSelectedIndex(-1);
		CMBDestination1.setSelectedIndex(-1);		
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNBook = new javax.swing.JButton();
        BTNExit = new javax.swing.JButton();
        CMBOXDeparture = new javax.swing.JComboBox<>();
        CMBDestination = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RADOneway = new javax.swing.JRadioButton();
        RADReturn = new javax.swing.JRadioButton();
        CMBOXDeparture1 = new javax.swing.JComboBox<>();
        CMBDestination1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        CHKTerms = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNBook.setText("BOOK ");
        BTNBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBookActionPerformed(evt);
            }
        });

        BTNExit.setText("EXIT");
        BTNExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNExitActionPerformed(evt);
            }
        });

        CMBOXDeparture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMBOXDepartureActionPerformed(evt);
            }
        });

        jLabel1.setText("Departure");

        jLabel2.setText("Destination");

        jLabel3.setText("NAME ");

        RADOneway.setText("ONE WAY");
        RADOneway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADOnewayActionPerformed(evt);
            }
        });

        RADReturn.setText("RETURN");
        RADReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADReturnActionPerformed(evt);
            }
        });

        CMBOXDeparture1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMBOXDeparture1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Departure");

        jLabel5.setText("Destination");

        CHKTerms.setText("TERMS AND CONDTIONS");
        CHKTerms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHKTermsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RADReturn)
                            .addComponent(RADOneway))
                        .addGap(18, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CMBDestination1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                    .addComponent(CMBOXDeparture1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(25, 25, 25))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(23, 23, 23)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(CMBDestination, javax.swing.GroupLayout.Alignment.LEADING, 0, 324, Short.MAX_VALUE)
                                        .addComponent(CMBOXDeparture, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TxtName, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addComponent(BTNExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNBook, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(CHKTerms, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CMBOXDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(RADOneway))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CMBDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(RADReturn)))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CMBOXDeparture1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBDestination1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNBook)
                    .addComponent(BTNExit)
                    .addComponent(CHKTerms))
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void CMBOXDepartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMBOXDepartureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMBOXDepartureActionPerformed

    private void RADOnewayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADOnewayActionPerformed
        // TODO add your handling code here:
        
      //  RADOneway.setSelected(false);
      enableLeg2(false);
   
          
    
       
    }//GEN-LAST:event_RADOnewayActionPerformed

    private void CMBOXDeparture1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMBOXDeparture1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMBOXDeparture1ActionPerformed

    private void BTNExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNExitActionPerformed

          System.exit(0);

          
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNExitActionPerformed

    private void BTNBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBookActionPerformed
        // TODO add your handling code here:
        
        
          String DepartureOway=CMBOXDeparture.getSelectedItem().toString();
          String DestinationOway=CMBDestination.getSelectedItem().toString();
          String DepartureReturn=CMBOXDeparture1.getSelectedItem().toString();
          String DestinationReturn=CMBDestination1.getSelectedItem().toString();
        
          String Name=TxtName.getText();
        
          String sFileName = "./Bookingfile.csv";
          
          
       
          
          if(DepartureOway == null ? DestinationOway == null : DepartureOway.equals(DestinationOway)){
                 
          JOptionPane.showMessageDialog(null, "Departure and destination Cannot be the same !!! Please start Again");
        CMBOXDeparture.setSelectedIndex(-1);
        CMBDestination.setSelectedIndex(-1);	
        
        CMBOXDeparture1.setSelectedIndex(-1);
        CMBDestination1.setSelectedIndex(-1);	
          
          
          }
          else {
 
          
         
         try
	(FileWriter writer = new FileWriter(sFileName)) {
		
      
            writer.append(Name);
	    writer.append(',');
	    writer.append(DepartureOway);
	    writer.append(',');
	    writer.append(DestinationOway);
            writer.append(',');	
	    writer.append(DepartureReturn);
	    writer.append(',');
	    writer.append(DestinationReturn);
	    writer.append('\n');
			
	    //generate whatever data you want
			
	    writer.flush();
            
	}
	catch(IOException e)
	{
	} 
        
        JOptionPane.showMessageDialog(null, "Name:" +  Name + " "+ "\nDeparture:" +DepartureOway  + " "+"\nDestination" + DestinationOway + " "+" \nDeparture Return :"+ " "+ DepartureReturn +
        
        " \nDestination Return" + DestinationReturn );
          } 
    }//GEN-LAST:event_BTNBookActionPerformed

    private void CHKTermsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHKTermsActionPerformed
        // TODO add your handling code here:
        CHKTerms.setSelected(true);
        
    }//GEN-LAST:event_CHKTermsActionPerformed

    private void RADReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADReturnActionPerformed
        // TODO add your handling code here:
     //   RADReturn.setSelected(false);
        
      
       enableLeg2(true);
    
        
    }//GEN-LAST:event_RADReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BOOKING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BOOKING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BOOKING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BOOKING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            
            
            @Override
            public void run() {
                try {
                    new BOOKING().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(BOOKING.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

  
    public ArrayList<String> lst = new ArrayList<String>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBook;
    private javax.swing.JButton BTNExit;
    private javax.swing.JCheckBox CHKTerms;
    public javax.swing.JComboBox<String> CMBDestination;
    public javax.swing.JComboBox<String> CMBDestination1;
    public javax.swing.JComboBox<String> CMBOXDeparture;
    public javax.swing.JComboBox<String> CMBOXDeparture1;
    private javax.swing.JRadioButton RADOneway;
    private javax.swing.JRadioButton RADReturn;
    private javax.swing.JTextField TxtName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
